Add Navigator documentation
webforj/webforj-docs pull request #126
Opened 2024-03-19 12:46 UTC by MatthewHawkins

2024-03-19 13:44 UTC, hyyan requested changes

2024-03-19 13:44 UTC, hyyan commented on docs/components/navigator.md
> +path='https://demo.webforj.com/webapp/controlsamples/NavigatorPages?'
isn't this the same demo the previous one ?

2024-03-19 13:44 UTC, hyyan commented on docs/components/navigator.md
> +You can customize tooltips for various parts of the Navigator component using the setTooltipText() method. Tooltips provide helpful hints to users when they hover over navigation elements.
setTooltipText() should be in backticks

2024-03-19 13:44 UTC, hyyan commented on docs/components/navigator.md
> +path='https://demo.webforj.com/webapp/controlsamples/NavigatorTable?'
This demo is not rendering correctly

2024-03-19 13:44 UTC, hyyan commented on docs/components/navigator.md
> +## Events
Remove [https://github.com/webforj/webforj-docs/issues/121](https://github.com/webforj/webforj-docs/issues/121)

2024-03-19 13:44 UTC, hyyan commented on docs/components/navigator.md
> +The concept of "pages" in the `Paginator` refers to the logical divisions of the entire dataset. Each page contains a specific number of items, and users navigate through these pages to explore the c
remove double quotes around pages

2024-03-19 13:44 UTC, hyyan commented on docs/components/navigator.md
> +path='https://demo.webforj.com/webapp/controlsamples/NavigatorBasic?'
Wrong demo

2024-03-19 13:44 UTC, hyyan commented on docs/components/navigator.md
> +<ComponentDemo
This demo looks like it is for  Quick jump layout, move it to the top

2024-03-19 13:46 UTC, hyyan requested changes

2024-03-19 13:46 UTC, hyyan commented on docs/components/navigator.md
> +<DocChip tooltipText="The name of the web component that will render in the DOM." label="dwc-navigator" href="https://basishub.github.io/basis-next/#/web-components/dwc-button" clickable={false} icon
why it says dwc-button

2024-03-19 13:46 UTC, hyyan commented on docs/components/navigator.md
> +<JavadocLink type="engine" location="com/webforj/component/layout/navigator/Navigator" top='true'/>
this should be : com/webforj/component/navigator/Navigator

2024-03-19 14:22 UTC, hyyan commented on docs/components/navigator.md
> +See [this section](#events) for more details on the available `Navigator` events.
remove this too

2024-03-19 14:31 UTC, hyyan commented on docs/components/navigator.md
> +<JavadocLink type="engine" location="com/webforj/component/layout/navigator/Navigator" top='true'/>
The url still wrong , component is doubled in the URL

2024-03-19 14:39 UTC, hyyan commented on docs/components/navigator.md
> +## Pagination
This section should explain that the navigator can accept a Paginator instance. When integrating with a Paginator, the navigator will respond to any changes within the Paginator. Additionally, this guide includes practical code snippets to illustrate how this integration works in practice.

2024-03-20 08:15 UTC, hyyan commented on docs/components/navigator.md
> +### Button and component text
That should be : "Buttons ..." (plural)

2024-03-20 08:20 UTC, hyyan requested changes

2024-03-20 08:20 UTC, hyyan commented on docs/components/navigator.md
> +## Best practices
please change to :

Understand dataset
Choose appropriate layout
Customize text and tooltips

2024-03-20 08:32 UTC, hyyan commented on docs/styling/getting_started.md
> +pagination_prev: "components/tabbed-pane"
why this change ?

2024-03-20 08:33 UTC, hyyan commented on src/components/DocsTools/ComponentDemoMultiple.js
> +    padding: ${padding || "1em"};
Move this outside the PR and send it in its own PR, this change is causing issues in splitter demos , test it more

2024-03-21 12:20 UTC, MatthewHawkins commented on docs/styling/getting_started.md
> +pagination_prev: "components/tabbed-pane"
Happed due to a rebase on website

2024-03-21 12:20 UTC, MatthewHawkins commented on src/components/DocsTools/ComponentDemoMultiple.js
> +    padding: ${padding || "1em"};
Fixed this

2024-03-21 12:38 UTC, hyyan approved these changes

2024-03-21 12:38 UTC, merged