Web storage docs
webforj/webforj-docs pull request #161
Opened 2024-06-13 22:38 UTC by gosteenBASIS

Web storage docs page completed to the best of my knowledge, with a couple caveats: 
- Not sure where it should go in the project structure. Currently placed under "Architecture."
- Have not actually tested the sample code, although it appears correct based on the Javadocs
- Note about the default 30-day expiration of the CookieStorage is based on comments in the code; have not verified otherwise.
- According to the Javadocs, it looks like you can pass attributes to the constructors for SessionStorage and LocalStorage, but based on some brief research it doesn't look like they can actually take attributes like cookies do. I have omitted any mention of attributes in the sample code and description for those sections.

2024-06-14 22:45 UTC, MatthewHawkins commented
Hey @gosteenBASIS, thanks for finishing this up, looks good!

- I asked Hyyan where he would like the article to be put within the hierarchy, and will do that once he answers before I ask for his review
- I tested and ran into a small issue that I'm hammering out with Hyyan. We can talk about testing code for the next few articles at some point next week

Thanks again, and once Hyyan and I tie up things, we'll get this merged!

2024-06-17 15:29 UTC, MatthewHawkins approved these changes

2024-06-18 07:16 UTC, hyyan requested changes

2024-06-18 18:49 UTC, gosteenBASIS commented on docs/advanced_topics/web-storage.md
> +:::info
Added title "Cookie Expiration" as a title for this note.

2024-06-19 18:47 UTC, gosteenBASIS commented on docs/advanced_topics/web-storage.md
> +| **Storage Size**   | ~4KB per cookie                              | Around 5-10MB                            | Around 5-10MB                            |
Hyyan, what numbers would you expect here? These numbers look correct from what I can tell.
4,096 bytes is the minimum size of a cookie that all browsers should support:
https://en.wikipedia.org/wiki/HTTP_cookie#Implementation

Most Web browsers seem to support either 10 MB for Local and Session storage, and at least 5 MB:
https://en.wikipedia.org/wiki/Web_storage#Storage_size

2024-06-19 18:55 UTC, gosteenBASIS commented on docs/advanced_topics/web-storage.md
> +- Small storage size (about 4KB)
The 4 KB limit seems to be widely accepted as a standard, and is a relevant consideration when using cookies. I would recommend we keep the specific size limit here.
https://datatracker.ietf.org/doc/html/rfc6265#section-6

2024-06-20 06:06 UTC, hyyan commented on docs/advanced_topics/web-storage.md
> +:::tip
Give this tip a title please

2024-06-20 06:06 UTC, hyyan commented on docs/advanced_topics/web-storage.md
> +| **Storage Size**   | ~4KB per cookie                              | Around 5-10MB                            | Around 5-10MB                            |
Thanks for sharing the source. Please include the links in the document

2024-06-20 06:08 UTC, hyyan commented on docs/advanced_topics/web-storage.md
> +- Small storage size (about 4KB)
OK. That's fine. Keep it after including the link for the sizes in the table above.

2024-06-24 06:57 UTC, hyyan approved these changes

2024-06-24 06:58 UTC, merged

2024-06-24 06:58 UTC, hyyan commented
@gosteenBASIS Looks Good. Thank you!