BrowserConsole Documentation
webforj/webforj-docs pull request #197
Opened 2024-07-31 15:50 UTC by bbrennanbasis

Pull request for a new page called "Console Logging" in "Advanced Topics".

2024-08-05 15:03 UTC, MatthewHawkins approved these changes

2024-08-12 06:19 UTC, hyyan requested changes

2024-08-12 06:19 UTC, hyyan commented on docs/advanced_topics/console-logging.md
> +```java
at the top of this code block , show how to import the method staticlly :

```
import static com.webforj.App.console;
```

2024-08-12 06:19 UTC, hyyan commented on docs/advanced_topics/console-logging.md
> +:::note
remove this

2024-08-12 06:22 UTC, hyyan commented
@bbrennanbasis  looks good, thanks. I asked for few minor changes

2024-08-12 15:08 UTC, hyyan requested changes

2024-08-12 15:08 UTC, hyyan commented on docs/advanced_topics/browser-console.md
> +Before `24.10`, the `App.consoleLog()` and `App.consoleErr()` methods enabled this behavior, but they have since been marked for deprecation.
Tha should be **App.consoleError**

2024-08-12 15:17 UTC, bbrennanbasis commented on docs/advanced_topics/browser-console.md
> +Before `24.10`, the `App.consoleLog()` and `App.consoleErr()` methods enabled this behavior, but they have since been marked for deprecation.
Ok, I've corrected that and corrected it in 24.10.md (The 24.10 blog post under Breaking changes > Console logging).

2024-08-12 15:22 UTC, hyyan commented
@bbrennanbasis please also fix the conflict with the `24.10.md`

2024-08-12 15:28 UTC, hyyan commented on docs/advanced_topics/browser-console.md
> +Before `24.10`, the `App.consoleLog()` and `App.consoleErr()` methods enabled this behavior, but they have since been marked for deprecation.
@bbrennanbasis Thanks, but this is causing a conflict with the latest content in the `24.10.md` file. You'll need to rebase the current branch onto the `website` branch first.

2024-08-13 06:52 UTC, hyyan approved these changes

2024-08-13 06:53 UTC, merged