Interval Documentation
webforj/webforj-docs pull request #198
Opened 2024-07-31 20:36 UTC by bbrennanbasis

Pull request to publish Interval documentation.

2024-08-05 11:57 UTC, MatthewHawkins requested changes
Looks good Ben! Go ahead and address the small changes I commented on and we'll pass this along. Once you've made the changes, please refresh/re-request a review.

2024-08-05 11:57 UTC, MatthewHawkins commented on docs/advanced_topics/interval.md
> +Optimized for the webforJ framework, it offers better performance compared to the standard Java timer or the Swing timer.
We'll want to check with Hyyan to ensure this is correct, but leave it for his review

2024-08-05 11:57 UTC, MatthewHawkins commented on docs/advanced_topics/interval.md
> +:::tip
I'd move this tip to the delay section

2024-08-05 14:21 UTC, bbrennanbasis commented on docs/advanced_topics/interval.md
> +Optimized for the webforJ framework, it offers better performance compared to the standard Java timer or the Swing timer.
I got the introduction information from the [Interval JavaDoc](https://javadoc.io/doc/com.webforj/webforj-foundation/latest/com/webforj/Interval.html), so if it is incorrect we'll want to change it there as well.

2024-08-05 14:26 UTC, bbrennanbasis commented on docs/advanced_topics/interval.md
> +:::tip
To clarify, do you mean the **Changing the Delay** section?

2024-08-05 14:28 UTC, MatthewHawkins commented on docs/advanced_topics/interval.md
> +:::tip
Correct :)

2024-08-05 14:29 UTC, MatthewHawkins commented on docs/advanced_topics/interval.md
> +Optimized for the webforJ framework, it offers better performance compared to the standard Java timer or the Swing timer.
Okay perfect - just wanted to make sure it was coming from our docs

2024-08-05 15:03 UTC, MatthewHawkins submitted a review, later dismissed

2024-08-06 08:03 UTC, hyyan requested changes

2024-08-06 08:03 UTC, hyyan commented on docs/advanced_topics/interval.md
> +    //... Grab 'pickedSpeed', the number from the NumberField as float value
what this comment means ?

2024-08-12 06:07 UTC, hyyan requested changes

2024-08-12 06:07 UTC, hyyan commented on docs/advanced_topics/interval.md
> +<JavadocLink type="foundation" location="com/webforj/Interval" top='true'/>
Remove this link

2024-08-12 06:07 UTC, hyyan commented on docs/advanced_topics/interval.md
> + use the start() method to initiate it. To halt the Interval, employ the stop() method. The restart() method can be used to restart the Interval.
This a duplication of the line after ?

2024-08-12 06:21 UTC, hyyan commented
@bbrennanbasis  looks good, thanks. I asked for few minor changes

2024-08-14 14:29 UTC, hyyan commented on docs/advanced_topics/interval.md
> +1. **Check for Inactivity**: Display a [`Dialog`](../components/dialog) component if there hasn't been any interaction on a form within a given time.
Dialog link is broken

2024-08-23 21:35 UTC, bbrennanbasis commented on docs/advanced_topics/interval.md
> +1. **Check for Inactivity**: Display a [`Dialog`](../components/dialog) component if there hasn't been any interaction on a form within a given time.
When testing on my local device, the link correctly went to Dialog, but an unrelated error popped up for every component page that uses the table builder.

2024-09-02 11:34 UTC, hyyan commented on docs/advanced_topics/interval.md
> +1. **Check for Inactivity**: Display a [`Dialog`](../components/dialog) component if there hasn't been any interaction on a form within a given time.
@MatthewHawkins could please check this issue with @bbrennanbasis

2024-09-02 13:00 UTC, MatthewHawkins commented on docs/advanced_topics/interval.md
> +1. **Check for Inactivity**: Display a [`Dialog`](../components/dialog) component if there hasn't been any interaction on a form within a given time.
Sure, will review in Thursday's meeting

2024-09-05 15:10 UTC, MatthewHawkins commented on docs/advanced_topics/interval.md
> +1. **Check for Inactivity**: Display a [`Dialog`](../components/dialog) component if there hasn't been any interaction on a form within a given time.
Checked the issue on the current branch and it works on dev version - should be fine on live.

2024-09-06 06:41 UTC, hyyan approved these changes

2024-09-06 06:41 UTC, merged