Toast Documentation
webforj/webforj-docs pull request #209
Opened 2024-08-21 06:21 UTC by gosteenBASIS

Here is a draft of the Toast documentation. It will probably have to wait until the corresponding Toast demos are published, but there are placeholders for the sample programs for now.

Please add your suggestions for any improvements!

2024-08-26 15:40 UTC, bbrennanbasis commented on docs/components/toast.md
> +## Actions and interactivity
Capitalize the I in Interactivity.

2024-08-27 18:58 UTC, gosteenBASIS commented on docs/components/toast.md
> +## Actions and interactivity
I believe we are using Google's style guide, which states that we should use sentence case for headings:
https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings

2024-08-27 19:03 UTC, gosteenBASIS commented on docs/components/toast.md
> +## Usage
Thanks for the suggestion Ben; I changed this heading to "Creating a toast notification"

2024-09-11 23:52 UTC, gosteenBASIS commented
@MatthewHawkins Can you review the updates I made to the Toast documentation?

2024-09-12 10:06 UTC, MatthewHawkins requested changes

2024-09-12 10:06 UTC, MatthewHawkins commented on docs/components/toast.md
> +A `Toast` notification is a subtle and unobtrusive [pop-up notification](https://en.wikipedia.org/wiki/Pop-up_notification) designed to provide users with real-time feedback and information. These no
Let's remove the link here

2024-09-12 10:06 UTC, MatthewHawkins commented on docs/components/toast.md
> +## Creating a toast notification
In titles and in the text, please include the name of the component in backticks

2024-09-12 10:06 UTC, MatthewHawkins commented on docs/components/toast.md
> +/>
At the end, please include the <TableBuilder> component, which will build the required tables for styling information like in the other articles.

You'll need to add this entry to the _dwc_control_map.json file in components directory in docs:
"Toast":"dwc-toast",

Holler if you have a question about this!

2024-09-16 22:30 UTC, gosteenBASIS commented on docs/components/toast.md
> +<!-- Todo: Where are the Javadocs for Toast? -->
Thanks!

2024-09-16 23:03 UTC, gosteenBASIS commented on docs/components/toast.md
> +<!-- Todo: Where are the Javadocs for Toast? -->
Thanks!

2024-10-15 09:31 UTC, MatthewHawkins approved these changes

2024-10-16 10:30 UTC, hyyan commented
/rebase

2024-10-21 07:21 UTC, hyyan commented
@laurenic0l please update the demo URLs

2024-10-23 11:01 UTC, closed without merging