Pull Request to resolve Issue 226 - Icon Component
webforj/webforj-docs pull request #240
Opened 2024-09-23 15:54 UTC by bbrennanbasis

This pull request adds an article documenting the Icon component.

2024-10-01 20:57 UTC, gosteenBASIS requested changes
Looks good overall! I left some comments for suggested wording and style changes.

2024-10-01 20:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +
I think the very first sentence should introduce the webforJ Icon component specifically, and then move into the general benefits of icons. Something like:
The webforJ `Icon` component allows you to effortlessly include icons in your user interface. Icons are a fundamental...

2024-10-01 20:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +Using icons in your app creates visual cues for navigation and actions, which can reduce the amount of text needed and ultimately simplifying the user interface.
simplifying should be simplify here:
"... which can reduce the amount of text needed and simplify the user interface."

2024-10-01 20:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +Every `Icon` is designed as Scalable Vector Graphics (SVG) images, which means they can easily scale to any size without losing clarity or quality.
Make this singular by adding "a" and changing "images" to "image":
Every `Icon` is designed as **a** Scalable Vector Graphics (SVG) **image**, ...

2024-10-01 20:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +
I would add a brief definition here. Something like:
"An icon pool is a collection of commonly-used icons that enables easy access and reuse. By using icons from an icon pool, you can ensure that the icons in your app are recognizable and share a consistent style. WebforJ allows you to choose from three pools, or implement a custom icon pool."

2024-10-01 20:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +Using webforJ lets you have the flexibility to choose from three pools and use them as unique classes, without the hassle of downloading any of the icons directly.
I would change "Using webforJ lets you have" to "WebforJ gives you"

2024-10-01 20:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +Each pool has an extensive gallery of available and cost-free icons.
I would change "gallery of available and cost-free icons" to "collection of open source icons that are free to use." to emphasize that these icons are open source.

2024-10-01 20:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +Icons can be generated by using the names listed on the websites.
I think "Icons can be generated by using the names listed on the websites" could be more verbose, to make it a bit more clear where this information comes from:
"To include an icon in your app, all you need is the icon pool and the icon name. Browse the icon pool website for the icon you wish to use, and use the icon name as the parameter of the `create` method."

2024-10-01 20:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +
The design decisions of putting icons before or after text feels a bit superfluous and beyond the scope of our documentation -- I think we could remove these sections.

2024-10-01 20:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +Unless established, the icon will inherit the theme of its direct parent component.
"Unless established" feels like an awkward start to this sentence. I would say:
An `Icon` inherits the theme of its direct parent component, but you can override this by applying a theme to an `Icon` directly.

2024-10-01 20:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +Icon components come with 7 discrete themes built in for quick styling without the use of CSS. These themes are pre-defined styles that can be applied to icons to change their appearance and visual p
"They offer a quick and consistent way to customize the look of buttons throughout an application." references buttons instead of icons.

2024-10-01 20:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +
I think the Best practices section should be above the tables.

2024-10-01 20:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +1. `REUGLAR`: The outlined variate of icons. This is the default.
Typo here: `REUGLAR` should be `REGULAR`.

2024-10-01 20:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +Some components, like `PasswordField` and `TimeField`, have built-in icons to help convey meaning for end-users.
Remove hyphen from "end users."

2024-10-07 15:48 UTC, bbrennanbasis commented on docs/components/icon.md
> +
If either @hyyan or @MatthewHawkins find this section is unnecessary, I'll remove it.

2024-10-09 16:57 UTC, gosteenBASIS requested changes
Added a couple more review comments -- sorry if I should have caught these on the previous review! Overall it looks good and I think it's ready for Hyyan to review if you make those changes.

2024-10-09 16:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +Using icons in your app creates visual cues for navigation and actions, which can reduce the amount of text needed and simplify the user interface. You can choose from three icon pools and also gives
Edit resulted in a grammar error here:
"You can choose from three icon pools and also gives you the option to create new ones from scratch."

2024-10-09 16:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +Every `Icon` is designed as a Scalable Vector Graphics (SVG) image, which means they can easily scale to any size without losing clarity or quality.
Grammatical number mismatch here: "Every `Icon` is... which means they..."
Could either be "All `Icon`s are..." or "... which means it..."

2024-10-09 16:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +For those interested in creating their own pools, see [Creating custom pools](#creating-custom-pools).
Instead of "For those interested..." I think this could be more direct by saying, "If you are interested in creating your own icon pool..."

2024-10-09 16:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +Make sure to design icons with equal width and height, as icon components are designed to occupy a square space.
Put icon in backticks here: "as `Icon` components are designed..."

2024-10-09 16:57 UTC, gosteenBASIS commented on docs/components/icon.md
> +- **Use icons sparignly:** Too many icons can overwhelm users, so only use icons when they add clarity or reduce complexity.
Typo on "sparignly" here.

2024-10-10 06:31 UTC, hyyan commented
/rebase

2024-10-10 06:39 UTC, hyyan commented
@bbrennanbasis this one has merge conflicts

2024-10-11 16:00 UTC, bbrennanbasis commented
@hyyan I've resolved the merge conflicts and addressed the additional comments from @gosteenBASIS.

2024-10-16 15:07 UTC, bbrennanbasis commented
@hyyan have you had a chance to look at this PR again?

2024-10-17 21:52 UTC, bbrennanbasis commented
Since this branch was merged with `website` instead of rebased, it is difficult to track the file changes. For this reason, I created a new branch and a new PR (#283) to help reviewers.

2024-10-17 21:52 UTC, closed without merging