Component Basics Admonitions
webforj/webforj-docs pull request #248
Opened 2024-09-24 21:10 UTC by gosteenBASIS

Closes Issue #73 

*** Changes in the update may require the docusaurus instance to be restarted.

Created a "ComponentBasics" component in DocsTools. This is a simple "snippet" admonition to put at the top of Component articles, and it links to the "Component Basics" page under "Building UIs".

As part of this change, I have reworked some of the component management. All the Docs Tools components have been added to the global scope, so you can use them on any pages without specifically importing them. Thus, I have removed all the DocsTools import statements as well.

On my local instance, this change required an `npm restart` to take effect, and the pages will have errors if the change isn't in effect. So, this pull request may require us to restart the docusaurus instance in order to refresh the global scope that the components are now added to.

2024-09-25 08:37 UTC, MatthewHawkins requested changes
Looks great Garrison, only thing would be to please add this to the Spinner component. Great idea to add the components to the theme, thanks for doing that.

2024-09-26 08:05 UTC, MatthewHawkins approved these changes

2024-09-30 07:55 UTC, hyyan requested changes
We only need an admonition for articles that contain nested articles, not for every single one.

2024-10-01 19:04 UTC, gosteenBASIS commented
I removed the ComponentBasics component, and created a "ParentLink" component. Give this component the name of the parent, and it will add an admonition to the page with a link to the enclosing folder of the page. You can set the URL parameter if it needs to link somewhere else.
I have added this component to all the List and Field component pages.

2024-10-01 19:28 UTC, gosteenBASIS commented
I've added the DocCardList section at the bottom of the fields and lists articles, and made some wording and language improvements. 
@MatthewHawkins @bbrennanbasis this is ready for review again.

2024-10-07 06:45 UTC, hyyan commented
@gosteenBASIS make sure to rebase

2024-10-07 16:25 UTC, bbrennanbasis reviewed
I have two comments for this PR.

1.  `<ComponentBasics />` is used in spinner.md and cases a runtime error, as it is undefined within the project.
2. Consider creating an admonition for the Option Dialogs, it could mention that they all from the [`com.webforj.component.optiondialog`](https://javadoc.io/doc/com.webforj/webforj-foundation/latest/com/webforj/component/optiondialog/package-summary.html) package.

2024-10-07 16:25 UTC, bbrennanbasis commented on docs/components/spinner/spinner.md
> +<ComponentBasics />
This is an undefined element in the project.

2024-10-08 03:13 UTC, gosteenBASIS commented on docs/components/spinner/spinner.md
> +<ComponentBasics />
Thanks Ben; must have forgotten that one because I forgot it when I added the component. I've removed it now.

2024-10-08 03:16 UTC, gosteenBASIS commented
@hyyan I've merged this branch with the website branch, and addressed Ben's comments. I think it's ready for review again.

2024-10-09 12:55 UTC, hyyan approved these changes

2024-10-09 12:55 UTC, merged