PR Added Slot section to ComboBox and ChoiceBox
webforj/webforj-docs pull request #253
Opened 2024-09-26 19:57 UTC by bbrennanbasis

- Added a section to the ComboBox and ChoiceBox pages talking about the prefix and suffix slots
-This PR closes #225.

2024-09-27 15:39 UTC, bbrennanbasis commented
@MatthewHawkins If the phrasing of these sections looks good to you, I'll make similar edits for Issues #224 and #222.

2024-09-30 08:44 UTC, MatthewHawkins submitted a review, later dismissed

2024-09-30 08:49 UTC, hyyan requested changes

2024-09-30 08:49 UTC, hyyan commented on docs/components/lists/choice-box.md
> +  choiceBox.setPrefixComponent(new Img("http://localhost:8888/joystick.png"));
Please the usage of `Img` with Icons

2024-10-01 07:25 UTC, hyyan commented
@bbrennanbasis please rebase and resolve conflicts

2024-10-01 14:36 UTC, bbrennanbasis commented
@hyyan ok, it should be rebased now

2024-10-02 07:27 UTC, hyyan approved these changes

2024-10-02 07:27 UTC, hyyan approved these changes

2024-10-02 07:28 UTC, merged