Spinner and Loading/BusyIndicator Docs
webforj/webforj-docs pull request #264
Opened 2024-10-02 15:37 UTC by laurenic0l

First draft of Spinner and Loading/BusyIndicator docs

2024-10-07 07:07 UTC, hyyan requested changes
@laurenic0l, please:

1. Fix all Vale issues.
2. Why is the loading and busy indicator included under the spinner section? It should have its own article.
3. The explanation of the loading and busy indicators feels disjointed, making it easy for the reader to lose track. The differences and scope of usage for these two components should be clarified from the beginning before moving on to explain their common features.

2024-10-10 06:31 UTC, hyyan commented
/rebase

2024-10-10 08:19 UTC, hyyan commented
@laurenic0l, please update the demo URLs to point to the correct programs.

2024-10-10 08:24 UTC, hyyan commented
@laurenic0l check https://github.com/webforj/webforj-docs/pull/248 and update the documentation accordingly.

2024-10-10 09:13 UTC, hyyan commented on docs/components/spinner-loading-busy/busyindicator.md
> +While the `Loading` component focuses on specific areas or components within the app, the `BusyIndicator` handles global, app-wide processes and blocks interaction across the entire interface. This d
link the "`Loading`" article here

2024-10-10 09:15 UTC, hyyan commented on docs/components/spinner-loading-busy/busyindicator.md
> +You can use methods like `setSpinnerSize()`, `setSpinnerSpeed()`, `setSpinnerClockwise()`, `setSpinnerTheme()`, and `setSpinnerVisible()` to adjust these properties of the spinner within your `BusyIn
remove this section please

2024-10-10 09:16 UTC, hyyan commented on docs/components/spinner-loading-busy/busyindicator.md
> +The `BusyIndicator` component in webforJ allows you to display a backdrop to block user interaction while a process is ongoing. By default, the component enables the backdrop, but you have the option
Use 'turn off' or 'off' instead of 'disable'

2024-10-10 09:17 UTC, hyyan commented on docs/components/spinner-loading-busy/busyindicator.md
> +<TableBuilder tag={require('@site/docs/components/_dwc_control_map.json').Loading} table='parts' exclusions=''/>
Tables are not loading

2024-10-10 09:19 UTC, hyyan commented on docs/components/spinner-loading-busy/loading.md
> +The `Loading` component in webforJ displays an overlay that indicates the system is processing an operation, temporarily blocking user interaction until the task completes. This component enhances us
rewrite :

The `Loading` component in webforJ displays an overlay that signals the processing of an operation, temporarily preventing user interaction until the task is complete. This feature improves the user experience, especially in situations where tasks like data loading, computations, or background processes may take some time.

2024-10-10 09:19 UTC, hyyan commented on docs/components/spinner-loading-busy/loading.md
> +Creating a `Loading` component in a webforJ app is a straightforward process.
remove this line

2024-10-10 09:21 UTC, hyyan commented on docs/components/spinner-loading-busy/loading.md
> +You can use methods like `setSpinnerSize()`, `setSpinnerSpeed()`, `setSpinnerClockwise()`, `setSpinnerTheme()`, and `setSpinnerVisible()` to adjust these properties of the spinner within your `Loadin
remove this section

2024-10-10 09:21 UTC, hyyan commented on docs/components/spinner-loading-busy/loading.md
> +<TableBuilder tag={require('@site/docs/components/_dwc_control_map.json').Loading} table='parts' exclusions=''/>
Tabler are not loading

2024-10-10 17:16 UTC, laurenic0l commented
Applied changes requested.

@hyyan this is ready for review again.

2024-10-11 08:33 UTC, hyyan commented on docs/components/busy/busyindicator.md
> +<JavadocLink type="busyindicator" location="com/webforj/component/spinner/Loading" top='true'/>
This link is broken

2024-10-11 08:49 UTC, hyyan requested changes

2024-10-11 08:49 UTC, hyyan commented on docs/components/busy/busyindicator.md
> +While the [`Loading`](../spinner-loading-busy/loading.md) component focuses on specific areas or components within the app, the `BusyIndicator` handles global, app-wide processes and blocks interacti
the loading link is broken

2024-10-11 08:49 UTC, hyyan commented on docs/components/loading/loading.md
> +The `Loading` component in webforJ displays an overlay that signals the processing of an operation, temporarily preventing user interaction until the task is complete. This feature improves the user
Mention the `BusyIndicator` with a link here also

2024-10-11 08:49 UTC, hyyan commented on docs/components/loading/loading.md
> +/>
change the height so the whole demo is visible

2024-10-11 08:49 UTC, hyyan commented on docs/components/spinner/spinner.md
> +To pause and resume the Spinner, use the setPaused() method. This is particularly helpful when you need to temporarily stop the spinning animation.
use backticks for setPaused()

2024-10-11 08:52 UTC, hyyan commented
@laurenic0l Looks good. I've requested a few minor changes. @MatthewHawkins, please give it a final review to ensure I didn't miss anything.

2024-10-11 14:59 UTC, laurenic0l commented
@hyyan applied changes. @MatthewHawkins, please let me know if there's anything else I need to change.

2024-10-15 10:11 UTC, MatthewHawkins approved these changes
Looks good, nice work!

2024-10-15 10:13 UTC, MatthewHawkins commented
@hyyan I reviewed the articles with the demos, looks good on my end.

2024-10-16 09:52 UTC, hyyan submitted a review, later dismissed

2024-10-16 10:05 UTC, hyyan commented
@laurenic0l Looks great! It will be merged together with the demos PR soon.

2024-10-16 10:07 UTC, hyyan commented
@laurenic0l, could you please review the unused CSS and remove it? Thanks!

2024-10-16 10:25 UTC, hyyan commented
@laurenic0l could you please also link the new docs in the [components gallery](https://documentation.webforj.com/docs/components/overview#).

2024-10-16 18:52 UTC, laurenic0l commented
@hyyan the unnecessary css has been removed and new docs have been linked in the components gallery.

2024-10-17 10:20 UTC, merged