PR - Added Opening and Closing section for ComboBox and ChoiceBox
webforj/webforj-docs pull request #267
Opened 2024-10-07 17:47 UTC by bbrennanbasis

This PR closes #67 .
The Opening and Closing sections, added under Max Row Count, also briefly mention that event listeners are available for these actions.

2024-10-10 06:30 UTC, hyyan commented
/rebase

2024-10-10 08:08 UTC, hyyan requested changes

2024-10-10 08:08 UTC, hyyan commented on docs/components/lists/combo-box.md
> +## Opening and Closing
'Opening and Closing' should use sentence-style capitalization

2024-10-10 08:08 UTC, hyyan commented on docs/components/lists/combo-box.md
> +Additionally, webforJ has event listeners for when the `ComboBox` is closed and when it's opened, giving you more control to trigger specific actions.
Add some code snippets

2024-10-11 21:49 UTC, bbrennanbasis commented on docs/components/lists/combo-box.md
> +## Opening and Closing
Corrected the capitalization for this section and the rest of the sections.

2024-10-11 21:52 UTC, bbrennanbasis commented on docs/components/lists/combo-box.md
> +Additionally, webforJ has event listeners for when the `ComboBox` is closed and when it's opened, giving you more control to trigger specific actions.
Here is the following code snippet I've added:

```
//Change the focus to the next component in a form
ComboBox university = new ComboBox("University");
ComboBox major = new ComboBox("Major");
Button submit = new Button("Submit");

//... Add lists of universities and majors

university.onClose( e ->{
  major.focus();
});

major.onClose( e ->{
  submit.focus();
});
```

2024-10-14 11:12 UTC, hyyan approved these changes

2024-10-14 11:13 UTC, merged