PR: Icon Component Article
webforj/webforj-docs pull request #283
Opened 2024-10-17 21:49 UTC by bbrennanbasis

This PR closes #226. 

Changes in this PR included:
- Created icon.md
- Deleted dwc-icon.md
- Added a hyperlink to icon.md on the component overview page

**Note**: There will be merge conflicts with this and PR #280 because of the deletion of dwc-icon.md.

2024-10-21 07:45 UTC, hyyan requested changes

2024-10-21 07:45 UTC, hyyan commented on docs/components/icon.md
> +WebforJ gives you the flexibility to choose from three pools and use them as unique classes, without the hassle of downloading any of the icons directly.
should be `webforJ`

2024-10-21 07:45 UTC, hyyan commented on docs/components/icon.md
> +Icon image = FeatherIcon.create("image");
`FeatherIcon` builder does not allow to create an icon from string name.

2024-10-21 07:45 UTC, hyyan commented on docs/components/icon.md
> +## Adding icons to components
This section should be rephrased to avoid listing the specific components that support prefix and suffix slots, as more components will support this in the future. Instead, it should be more general, stating that some components currently support this feature that implement the `HasPrefixAndSuffix` interface, allowing for the use of prefix and suffix icons or other valid components.

2024-10-21 07:45 UTC, hyyan commented on docs/components/icon.md
> +## Creating custom pools
This will need working code sample. Check https://github.com/webforj/webforj/pull/717

2024-10-21 07:45 UTC, hyyan commented on docs/components/icon.md
> + FlexLayout layout = FlexLayout.create().horizontal().build().setMargin("var(--dwc-space-m)");
show only the relevant part:

```java
IconButton bell = new IconButton(FeatherIcon.BELL.create());
bell.onClick(e -> showMessageDialog("You have a new message!", "Ding Dong!"));
```

2024-10-21 07:45 UTC, hyyan commented on docs/components/icon.md
> +### Expanses
should the `Below is information on the attributes, as well as parts and properties required for customizing icons with CSS.` be removed , why it is in here ?

2024-10-21 07:47 UTC, hyyan commented
@bbrennanbasis Overall, everything looks good. I've requested a few changes. Also, please address all the Vale issues.  
@MatthewHawkins The article still needs a few runnable demos. Who will be working on those?

2024-10-21 08:21 UTC, MatthewHawkins commented
@laurenic0l Would you please read through this article, determine one or two spots for demo programs to be created, and then create them please?

@bbrennanbasis Let me know if you want a hand with any of the Vale comments - the components imports should be able to be removed as they're now globally available to all articles, and I'm happy to help with any others.

2024-10-21 15:31 UTC, bbrennanbasis commented on docs/components/icon.md
> +### Expanses
The Expanses section was text from [dwc-icon styling](https://documentation.webforj.com/docs/components/dwc-icon#expanses). I'll go ahead and remove it.

2024-10-21 18:50 UTC, bbrennanbasis commented
@hyyan Included your review request, rebased, and included a link on the `Button` article.

This PR now also closes #177 and #287.

2024-10-23 11:01 UTC, hyyan commented
@laurenic0l, please include the demo URLs once you're finished.

2024-10-28 11:10 UTC, hyyan commented
@bbrennanbasis could merge these two sections and streamline the wording a bit: "Icons before component text" and "Icons after component text."

@laurenic0l The sections "Icons before component text" and "Icons after component text" need an sample.

2024-10-28 11:11 UTC, hyyan commented on docs/components/icon.md
> +## Creating custom pools
@bbrennanbasis, this should be a code sample only, not a complete runnable demo.

2024-10-28 19:48 UTC, bbrennanbasis commented
@hyyan I've added the custom pool code snippet and consolidated the "Icons before component text" and "Icons after component text" sections to "Icon placement: before VS after".

2024-10-30 14:29 UTC, hyyan commented on docs/components/icon.md
> +   - Download ⬇
Remove these examples please , we a demo for this now

2024-10-30 16:01 UTC, bbrennanbasis commented
> @bbrennanbasis One last thing I noticed that’s still missing—could you briefly cover the Custom Pool Factory as well?

@hyyan I've added a section for this and removed the before and after examples using emojis.

2024-10-31 13:35 UTC, MatthewHawkins submitted a review, later dismissed
Custom Icon pool section looks clear to me

2024-11-06 15:06 UTC, hyyan approved these changes

2024-11-13 13:21 UTC, merged