Rewrote configuration to emphasis singular `App` class usage
webforj/webforj-docs pull request #288
Opened 2024-10-21 23:01 UTC by bbrennanbasis

This PR closes #231.

2024-10-23 10:58 UTC, hyyan requested changes

2024-10-23 10:58 UTC, hyyan commented on docs/getting-started/configuration.md
> +### Running a specific program
@MatthewHawkins I believe this section is misplaced and doesn't belong in the configuration section. Additionally, routing is optional anyway. what do you think ?

2024-10-23 10:59 UTC, hyyan commented
@bbrennanbasis It looks good. Please review all the Vale issues on this page and ensure they are fixed. Thank you!

2024-10-28 20:13 UTC, bbrennanbasis commented
@hyyan I removed the specific step-by-step instructions for routing and mentioned the other way of running a specific app (using the class that extends `App`).

2024-10-29 12:12 UTC, hyyan commented
@MatthewHawkins, please review this and check if it aligns with the plans for documenting the new configuration approach. It might be best to hold off until you've completed that.

2024-10-31 13:32 UTC, MatthewHawkins commented
@hyyan I read over the changes here and it looks better to me. I'm not opposed to merging before the new WAR configuration is documented, as I believe enforcing this behavior with the routing changes implemented is sufficient, but if you'd prefer to wait until that's completed, then no problem.

2024-11-06 15:14 UTC, hyyan requested changes

2024-11-06 15:15 UTC, hyyan commented
@bbrennanbasis requested minor formatting changes
@MatthewHawkins merge when ready please

2024-11-06 16:23 UTC, bbrennanbasis commented
@hyyan 
- Changed application to app
- Removed misleading wording talking about with and without the plugin
- Rewrote Default class section and changed the header name

2024-11-07 16:05 UTC, MatthewHawkins approved these changes

2024-11-07 16:05 UTC, merged