PR - Updated Toast Doc
webforj/webforj-docs pull request #289
Opened 2024-10-22 11:59 UTC by laurenic0l

Updated the Toast doc, links, etc.

closes #180

2024-10-23 11:08 UTC, MatthewHawkins submitted a review, later dismissed

2024-10-23 11:08 UTC, MatthewHawkins commented
@hyyan Tested with the updated demo URLs, everything here looks good to me, ready for your review.

2024-10-23 11:57 UTC, hyyan requested changes

2024-10-23 11:57 UTC, hyyan commented on docs/components/toast.md
> +```java
We should include a tip or note explaining that, unlike other components, a toast doesn't need to be added to a container. The `open` method will automatically attach the toast directly to the first app frame.

2024-10-23 11:57 UTC, hyyan commented on docs/components/toast.md
> +### Stacking
Should be `## Stacking`. Header level 2

2024-10-23 11:57 UTC, hyyan commented on docs/components/toast.md
> +## Usages
This section feels repetitive compared to the introduction. Let's merge the "Basics" and "Usages" sections, and use the sample from the "Basics" section here. The cookies demo can then be included in the "Actions and Interactivity" section.

2024-10-23 11:57 UTC, hyyan commented on docs/components/toast.md
> +### Shadow parts
The tables are not loading, and some are missing. Please check with other documents for reference.

2024-10-23 11:59 UTC, hyyan commented
@laurenic0l looks good overall. I requested few changes

2024-10-23 12:46 UTC, hyyan commented on docs/components/toast.md
> +## Usages
@laurenic0l, maybe wire the buttons to simply close the toast. ?

2024-10-24 10:25 UTC, hyyan submitted a review, later dismissed

2024-10-24 14:54 UTC, MatthewHawkins approved these changes

2024-10-24 14:56 UTC, merged