feat/docs: Adding browser history documentation draft
webforj/webforj-docs pull request #290
Opened 2024-10-23 14:15 UTC by MatthewHawkins

2024-10-24 10:44 UTC, hyyan requested changes

2024-10-24 10:44 UTC, hyyan commented on docs/advanced/browser-history.md
> +```
Let's remove this section

2024-10-24 10:44 UTC, hyyan commented on docs/advanced/browser-history.md
> +```
Let's remove this paragraph

2024-10-24 10:44 UTC, hyyan commented on docs/advanced/browser-history.md
> +- `go(int index)`: Navigates to a specific point in the history stack based on an index. A positive number moves forward, a negative number moves backward, and zero reloads the current page. This met
back() and forward() needs to be wrapped with backticks

2024-10-24 10:44 UTC, hyyan commented on docs/advanced/browser-history.md
> +```
mention https://javadoc.io/doc/com.webforj/webforj-foundation/latest/com/webforj/Request.html

2024-10-24 10:46 UTC, hyyan commented
@MatthewHawkins, it looks good overall. There's just one thing missing: explaining that you either initialize a new History object, or, if you're using routing, you can retrieve the created history instance from the router.

2024-10-24 10:46 UTC, hyyan commented
@MatthewHawkins also we need to address the issues related to value.

2024-10-28 09:59 UTC, MatthewHawkins commented
@hyyan - Made some changes, my first question is what you'd like me to mention specifically about the Request class (just to ensure I touch on all relevant points) https://javadoc.io/doc/com.webforj/webforj-foundation/latest/com/webforj/Request.html

Second thing would be discussing a couple vale rules I encountered here when we have time.

2024-10-28 10:06 UTC, hyyan approved these changes

2024-11-06 15:17 UTC, hyyan commented
@MatthewHawkins this is good to go

2024-11-07 10:08 UTC, merged