306 document the webforj war deployment method
webforj/webforj-docs pull request #311
Opened 2024-11-11 13:50 UTC by MatthewHawkins

TODO:

- BLS/Licensing section
- Remove hidden sidebar items on final approval of layout and update links
- Add deep linking to current articles
- Update maven install plugin section per [Hyyan's issue](https://github.com/webforj/webforj/issues/798)

2024-11-13 13:19 UTC, hyyan submitted a review, later dismissed
@MatthewHawkins as discussed, we still the redirect from `docs/installation/docker`to the new getting started section to be handled before this get merged

2024-11-13 15:11 UTC, MatthewHawkins commented
@hyyan Ready for your first pass review on the deployment/reload sections

2024-11-14 07:49 UTC, hyyan requested changes

2024-11-14 07:49 UTC, hyyan commented on docs/configuration/deploy-reload/jrebel.md
> +:::
Before running the command document the `Add the JRebel agent to MAVEN_OPTS`
https://manuals.jrebel.com/jrebel/standalone/launch-from-command-line.html#maven-jetty-plugin-mvn-jetty-run

2024-11-14 07:49 UTC, hyyan commented on docs/configuration/deploy-reload/jrebel.md
> +:::
Remove

2024-11-14 07:49 UTC, hyyan commented on docs/configuration/deploy-reload/maven-jetty.md
> +| **`scanIntervalSeconds`**         | Configures how often the Jetty server scans for file changes in the **`pom.xml`**. The skeleton project sets this to `2` seconds. Increasing this interval can re
The property name is `scan`, and it should be included in the POM file. This configuration table is both confusing and incorrect.

2024-11-14 07:49 UTC, hyyan commented on docs/configuration/deploy-reload/maven-jetty.md
> +| **`scanIntervalSeconds`**         | Configures how often the Jetty server scans for file changes in the **`pom.xml`**. The skeleton project sets this to `2` seconds. Increasing this interval can re
The skeleton sets this to `1`

2024-11-14 07:49 UTC, hyyan commented on docs/configuration/deploy-reload/maven-jetty.md
> +The [`skeleton-starter-hello-world`](https://github.com/webforj/skeleton-starter-hello-world) project sets this value to `8s` for development.
to `1s` not `8s`

2024-11-14 07:49 UTC, hyyan commented on docs/configuration/deploy-reload/maven-jetty.md
> +- **Memory and CPU usage**: Frequent file scanning, set by low `scanIntervalSeconds` values in the `pom.xml`, can increase resource consumption, especially on large projects. Increasing the interval
`scan` not `scanIntervalSeconds`

2024-11-14 07:49 UTC, hyyan commented on docs/configuration/deploy-reload/maven-jetty.md
> +- **Limited production use**: The Jetty Plugin is designed for development, not for production environments. It lacks the performance optimization and security configurations required for production,
This no limitation. Remove

2024-11-14 11:24 UTC, hyyan commented on docs/configuration/deploy-reload/jrebel.md
> +hide_table_of_contents: true
Dont hide ToC for articles

2024-11-25 08:19 UTC, hyyan commented on docs/intro/getting-started.md
> +```
Add a table to explain the different command params

2024-11-26 23:45 UTC, merged