chore: style improvements and enhancements to the Prerequisites page.
webforj/webforj-docs pull request #388
Opened 2024-12-10 18:57 UTC by gosteenBASIS

Since the Prerequisites page is one of the first pages users will see, I've improved the style, grammar, layout, and user-friendliness of the page.

2024-12-10 21:53 UTC, bbrennanbasis reviewed
@gosteenBASIS I've added my feedback for this PR.

2024-12-10 21:53 UTC, bbrennanbasis commented on docs/introduction/prerequisites.md
> +WebforJ requires Java 17 or higher to ensure compatibility with webforJ and access to the latest features and security updates of the Java ecosystem. WebforJ is compatible with official Oracle JDKs a
Avoid using webforJ at the beginning of the sentences. Consider the following rewrite:

The webforJ framework requires Java 17 or higher to ensure compatibility and access to the latest features and security updates of the Java ecosystem. Compatibility is provided with official Oracle JDKs and the open source Eclipse Temurin JDKs.

2024-12-10 21:53 UTC, bbrennanbasis commented on docs/introduction/prerequisites.md
>  ## Java Development Kit (JDK) 17 or higher
Should we add a note suggesting to use LTS releases?

2024-12-10 21:53 UTC, bbrennanbasis commented on docs/introduction/prerequisites.md
> +Getting started with webforJ is simple, because there are only a couple prerequisites. Use this guide to set up your development environment with the essential tools you will need to get up and runni
Change `only a couple prerequisites` to `only a couple  of prerequisites`.

2024-12-10 21:53 UTC, bbrennanbasis commented on docs/introduction/prerequisites.md
> +- Open-source JDKs can be found at Adoptium's [Eclipse Temurin™ Latest Releases](https://adoptium.net/temurin/releases/) page.
Use `open source` instead of `open-source`.

2024-12-10 21:53 UTC, bbrennanbasis commented on docs/introduction/prerequisites.md
> +- Official Oracle JDKs can be found at Oracle's [Java Downloads](https://www.oracle.com/java/technologies/downloads/) page.
can be found ~~at~~ on Oracle's

2024-12-10 21:53 UTC, bbrennanbasis commented on docs/introduction/prerequisites.md
> +  - Click the link that corresponds to your computer's architecture.
~~computer's architecture~~ operating system

2024-12-10 21:58 UTC, bbrennanbasis commented on docs/introduction/prerequisites.md
> +A Java Development Kit (JDK) is the most important requirement for developing with webforJ, providing the necessary tools to compile, run, and manage Java apps.
The acronym was used in the section header, so the sentence can start with: A JDK is the most...

2024-12-11 20:22 UTC, gosteenBASIS commented on docs/introduction/prerequisites.md
> +  - Click the link that corresponds to your computer's architecture.
No, the operating system is selected previously, and in this part we're specifically referring to the computer's architecture: x64, ARM64, etc.

2024-12-11 20:32 UTC, gosteenBASIS commented on docs/introduction/prerequisites.md
> +- Official Oracle JDKs can be found at Oracle's [Java Downloads](https://www.oracle.com/java/technologies/downloads/) page.
Updated this on and the Adoptium link.

2024-12-11 20:34 UTC, gosteenBASIS commented on docs/introduction/prerequisites.md
> +A Java Development Kit (JDK) is the most important requirement for developing with webforJ, providing the necessary tools to compile, run, and manage Java apps.
I'd rather leave this as-is because it's defining and introducing the concept of a JDK.

2024-12-12 16:19 UTC, gosteenBASIS commented on docs/introduction/prerequisites.md
> +WebforJ requires Java 17 or higher to ensure compatibility with webforJ and access to the latest features and security updates of the Java ecosystem. WebforJ is compatible with official Oracle JDKs a
@MatthewHawkins What are your thoughts on this? I prefer the wording with webforJ at the start of the sentence, otherwise we end up with awkward constructions with passive voice that aren't as clear. And I do think that we should capitalize it in cases where it's at the start of the sentence.

2025-01-08 10:35 UTC, hyyan commented on docs/introduction/prerequisites.md
> +## Setting up your development environment
Remove this title

2025-01-08 10:39 UTC, hyyan requested changes
The term "webforJ" is excessively repeated within a single paragraph, and it is written in different casing inconsistently.

2025-01-13 21:46 UTC, gosteenBASIS commented
I've reworded some sentences to avoid using webforJ at the beginning, and removed the first header as Hyyan requested.

2025-01-14 13:06 UTC, hyyan commented
/rebase

2025-01-14 20:27 UTC, MatthewHawkins approved these changes

2025-01-14 20:28 UTC, merged